### ISSUE TITLE
Build fails on Ubuntu older than 18.04 due to old cmake version

### ISSUE THREAD

**Issue by paskal** [paskal/SoftEtherVPN-debianisation#1]
[Example](https://launchpadlibrarian.net/392434884/buildlog_ubuntu-precise-amd64.softether-vpn_5.01.9658-0~201810081900~ubuntu12.04.1_BUILDING.txt.gz):

    cmake .
    CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
      CMake 3.7 or higher is required.  You are running version 2.8.7
[Proposed fix](https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/.gitlab-ci.yml#L7-L8) by @chipitsine should be applied.

**Comment by paskal** [comment]
The current error is:

    wget https://cmake.org/files/v/cmake-3.12.3.tar.gz && tar -xzf cmake-3.12.3.tar.gz
    --2018-10-09 14:13:38--  https://cmake.org/files/v/cmake-3.12.3.tar.gz
    Resolving cmake.org (cmake.org)... failed: Name or service not known.
    wget: unable to resolve host address ‘cmake.org’

This is getting tricky.

**Comment by chipitsine** [comment]
I played a bit with launchpad, seems it runs builds without network connectivity

**Comment by paskal** [comment]
It's indeed so, thanks for help! I've worked this around already and fixing newly found problems.

**Comment by paskal** [comment]
I've had to embed cmake source into `debian` folder and build it from source in case built in version is older than required, and also I've had to downgrade cmake to be able to build it with GCC without g++11 support under 12.04. Now it builds like a charm, and I see no problems left, feel free to reopen or create new issues in case of trouble.
