### ISSUE TITLE
Build for Trusty fails as it can't find cmake

### ISSUE THREAD

**Issue by Leden** [paskal/SoftEtherVPN-debianisation#3]
https://launchpadlibrarian.net/392470207/buildlog_ubuntu-trusty-amd64.softether-vpn_5.01.9660~201810081900~ubuntu14.04.1_BUILDING.txt.gz

```
---------------------------------------------
CMake has bootstrapped.  Now run make.
/<<PKGBUILDDIR>>
/bin/sh: 1: debian/cmake/bin/cmake: not found
make[1]: *** [override_dh_auto_configure] Error 127
make[1]: Leaving directory `/<<PKGBUILDDIR>>'
make: *** [build-arch] Error 2
dpkg-buildpackage: error: debian/rules build-arch gave error exit status 2
```

**Comment by paskal** [comment]
It's actually about wrong path to binary which is built above. If I run `make install` it dies with insufficient permissions, so I need to use cmake binary in-place (which I'm trying to achieve there but failed to set proper path).

**Comment by paskal** [comment]
Make command was missing, fixed now.
