### ISSUE TITLE
memory leak testing

### ISSUE THREAD

**Issue by chipitsine** [paskal/SoftEtherVPN-debianisation#5]
hi

`vpntest` utility was recently added to repo. for example, it might detect memory leaks
while we already run it on x64 CI, we would like to add non-x64 builds.

can you add it to x86 and armh launchpad builds ? (or to every build, it is not very time consuming)

here's an example, how to call it

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/.travis.yml#L62

**Comment by paskal** [comment]
I'll look into it.
@chipitsine, by the way current build [is failing](https://launchpadlibrarian.net/395354608/buildlog_ubuntu-cosmic-amd64.softether-vpn_5.01.9663~201810301647~ubuntu18.10.1_BUILDING.txt.gz) and release version is likely affected, could you please take a look? Only Ubuntu 12.04 is not affected, might be related to cmake version and the fact what it's built separately for Ubuntu 12.04.

**Comment by paskal** [comment]
@chipitsine, could you please write once more, why do you think this testing should be performed on builds? Does it return non-zero exit status on failure? E.g. do you think positive result need to block the build? Otherwise, what it's purpose, diagnostics you want to see in build logs for different platforms?

**Comment by paskal** [comment]
Added:
[amd64](https://launchpadlibrarian.net/400029622/buildlog_ubuntu-disco-amd64.softether-vpn_0%3A5.01.9665-1~201812020153~ubuntu19.04.1_BUILDING.txt.gz)
[arm64](https://launchpadlibrarian.net/400030095/buildlog_ubuntu-disco-arm64.softether-vpn_0%3A5.01.9665-1~201812020153~ubuntu19.04.1_BUILDING.txt.gz)
[armhf](https://launchpadlibrarian.net/400030089/buildlog_ubuntu-disco-armhf.softether-vpn_0%3A5.01.9665-1~201812020153~ubuntu19.04.1_BUILDING.txt.gz)
[i386](https://launchpadlibrarian.net/400029699/buildlog_ubuntu-disco-i386.softether-vpn_0%3A5.01.9665-1~201812020153~ubuntu19.04.1_BUILDING.txt.gz)
