### ISSUE TITLE
does not start after update

### ISSUE THREAD

**Issue by alexshalex** [paskal/SoftEtherVPN-debianisation#6]
Ubuntu 14.04.5 LTS
after update error:
```
Настраивается пакет softether-vpnserver (5.01.9663~201810312304~ubuntu14.04.1) …
Starting SoftEtherVPN Server: vpnserver/usr/libexec/softether/vpnserver/vpnserver: error while loading shared libraries: libcedar.so: cannot open shared object file: No such file or directory
invoke-rc.d: initscript softether-vpnserver, action "start" failed.
dpkg: ошибка при обработке пакета softether-vpnserver (--configure):
 подпроцесс установлен сценарий post-installation возвратил код ошибки 127
При обработке следующих пакетов произошли ошибки:
 softether-vpnserver
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by alexshalex** [comment]
fix did not fix the error
Настраивается пакет softether-vpnserver (5.01.9663~201811040311~ubuntu14.04.1) …
Starting SoftEtherVPN Server: vpnserver/usr/libexec/softether/vpnserver/vpnserver: error while loading shared libraries: libcedar.so: cannot open shared object file: No such file or directory
invoke-rc.d: initscript softether-vpnserver, action "start" failed.
dpkg: ошибка при обработке пакета softether-vpnserver (--configure):
 подпроцесс установлен сценарий post-installation возвратил код ошибки 127
Обрабатываются триггеры для ureadahead (0.100.0-16) …
При обработке следующих пакетов произошли ошибки:
 softether-vpnserver
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by paskal** [comment]
@davidebeatrici, could you please point me where to look at? I could alter the startup script if that's necessary.

**Comment by chipitsine** [comment]
а, собственно, libcedar.so у вас есть ? а что показывает `ldd /usr/libexec/softether/vpnserver/vpnserver` ?

**Comment by chipitsine** [comment]
я проинсталировал с `ppa:paskal-07/softethervpn` 
 нет библиотеки libcedar.so

эта библиотека сейчас упаковывается в `softether-common`

https://github.com/SoftEtherVPN/SoftEtherVPN/releases

вероятно, в вашей системе упаковки она не входит ни в какой пакет

**Comment by paskal** [comment]
I'll try to fix it till tomorrow's evening. @alexshalex, thank a lot for the report!

**Comment by paskal** [comment]
In progress, will be fixed shortly.

**Comment by chipitsine** [comment]
we enabled package install (and test restart) in App Veyor builds

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/.ci/appveyor_afterbuild.sh

is similar thing possible during launchpad builds ?

**Comment by paskal** [comment]
@alexshalex, it's fixed in 5.01.9666~201810221722 in [daily repo](https://launchpad.net/~paskal-07/+archive/ubuntu/softethervpn), nigthly is broken and will be fixed someday in the future.

**Comment by alexshalex** [comment]
in ubuntu 18.04
softether-vpnserver[17989]: Starting SoftEtherVPN Server: vpnserver/usr/libexec/softether/vpnserver/vpnserver: error while loading shared libraries: libcedar.so: cannot open shared object file: No such file or directory

**Comment by paskal** [comment]
Thanks for testing, I'm terribly sorry for confusion - original repo changed a lot, and changes go further than I thought. I've started new build on older version, please upgrade in a hour and give it a try.
As a sidenote, I need to introduce smoke test for package installation here via gitlab ci.

**Comment by alexshalex** [comment]
5.01.9667~201810150926~ubuntu14.04.1 and 5.01.9667~201810150926~ubuntu18.04.1 works for me

**Comment by paskal** [comment]
Build fixed, new version released. Resolving.
